### ISSUE TITLE
Felix Landing Page field bug

### ISSUE THREAD

**Issue by gtcattley** [sseefried/open-epidemic-game#1]
This is weird.

We created three landing pages for one of our clients (800515 - Atlas Copco).
I copied the URL from my browser, and added them to the new Landing Pages field (comma separated) on the Edit page:
 
![image](https://user-images.githubusercontent.com/30449668/31974692-d5b9a2e4-b978-11e7-9264-a09b7e7a1a7d.png)

Saved the changes, and the links appear on the front end correctly:
 
![image](https://user-images.githubusercontent.com/30449668/31974696-dbcb3b7a-b978-11e7-84f2-5902f4d26237.png)

Click on the link, and the site doesn't resolve:
 
![image](https://user-images.githubusercontent.com/30449668/31974702-df794a32-b978-11e7-8863-4cd82232e452.png)

Go back and check everything in the Edit screen, and all is correct.

Check hover over the link on the details page to ensure that the link is correct, and it is isn't:

 
![image](https://user-images.githubusercontent.com/30449668/31974707-e5c16e42-b978-11e7-97d3-f0d50d45bd89.png)

The colon is missing.

I didn't spot this the first time, but the browser displays:

 
![image](https://user-images.githubusercontent.com/30449668/31974709-ec2d7da2-b978-11e7-94d3-89df6df8d94d.png)

If I copy and paste the URL from the browser, I get:
**http://http//atlascopcorentals.com.au/nitrogen/**

With an additional 'http://' added to the URL.

I have fixed the issue above by not pasting the full URL with http:// into the field, and everything is working fine.

But it is a bug that should be resolved…

**Comment by raurir** [comment]
What the hell are you talking about? This is an open source game. Atlas what?

**Comment by sseefried** [comment]
Hehe, why are you subscribed to this? Looks like I gave the wrong link to
Graham, one of the people I work for. I'll close this issue and move it
over to the correct project.
